apiVersion: v1
appVersion: "1.0.1"
description: A Helm chart for express-crud application
name: express-crud
version: 0.1.0
sources:
- https://github.com/jainishshah17/express-mongo-crud
maintainers:
- name: jainishshah17
  email: jainishshah@yahoo.com
icon: https://github.com/jainishshah17/jainishshah.com/blob/master/app/public/images/logo.jpg
home: http://jainishshah.com/